apiVersion: apps/v1
kind: Deployment
metadata:
  name:  bkacad-db01
  labels:
    app:  bkacad-db01
spec:
  selector:
    matchLabels:
      app: bkacad-db01
  replicas: 1
  template:
    metadata:
      labels:
        app:  bkacad-db01
    spec:
      containers:
        - name:  bkacad-db01
          image:  kiettran164/vprofiledb:v1
          volumeMounts:
            - mountPath: /var/lib/mysql
              name: mysql-pv-data
          ports:
            - name: db01-port
              containerPort: 3306
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: app-secret
                  key: db-pass
      volumes:
        - name: mysql-pv-data
          persistentVolumeClaim:
            claimName: mysql-pv-data-claim
        