apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-pv-data
spec:
  accessModes:
    - ReadWriteMany
  capacity:
    storage: 5Gi
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: 192.168.12.52
    path: "/mnt/data"
  
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pv-data-claim
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi