apiVersion: v1
kind: Service
metadata:
  name: bkacad-rabbitmq01
spec:
  ports:
    - port: 15672
      targetPort: rabbit-port
      protocol: TCP
  selector:
    app: bkacad-rabbitmq01
  type: ClusterIP