apiVersion: apps/v1
kind: Deployment
metadata:
  name:  bkacad-rabbitmq01
  labels:
    app: bkacad-rabbitmq01
spec:
  selector:
    matchLabels:
      app: bkacad-rabbitmq01
  replicas: 1
  template:
    metadata:
      labels:
        app: bkacad-rabbitmq01
    spec:
      containers:
      - name: bkacad-rabbitmq01
        image: rabbitmq
        ports:
          - name: rabbit-port
            containerPort: 15672
        env:
          - name: RABBITMQ_DEFAULT_PASS
            valueFrom:
              secretKeyRef:
                name: app-secret
                key: rmq-pass
          - name: RABBITMQ_DEFAULT_USER
            value: "guest"
